# WandB Sweep Configuration for RandomBrightnessContrast Optimization
# 베스트 파라미터는 고정하고, RandomBrightnessContrast augmentation만 최적화

method: bayes  # bayes, grid, random
metric:
  name: val/hmean
  goal: maximize

parameters:
  # RandomBrightnessContrast 파라미터 (train_transform.transforms[3])

  # 밝기 조정 범위 (현재값: 0.2)
  brightness_limit:
    min: 0.1
    max: 0.5

  # 대비 조정 범위 (현재값: 0.2)
  contrast_limit:
    min: 0.1
    max: 0.5

  # augmentation 적용 확률 (현재값: 0.5)
  brightness_contrast_p:
    min: 0.1
    max: 0.7

# 프로젝트 설정 (환경변수로 오버라이드 가능)
project: OCR-Brightness-Sweep
entity: null  # WANDB_ENTITY 환경변수 사용