method: bayes
metric:
  name: test/hmean
  goal: maximize
parameters:
  thresh:
    min: 0.15
    max: 0.25
  box_thresh:
    min: 0.40
    max: 0.46
  box_unclip_ratio:
    min: 1.30
    max: 2.00
  polygon_unclip_ratio:
    min: 1.30
    max: 2.10
project: ocr-postprocess
entity: null
