# @package _global_

models:
  decoder:
    _target_: ${decoder_path}.UNet
    in_channels: [128, 256, 512, 1024]  # Channels for hrnet_w44 with select_features [1,2,3,4]
    strides: [4, 8, 16, 32]           # Input layer scale like convnext
    inner_channels: 256               # Hidden layer channel
    output_channels: 64               # output layer channel
    bias: False
