# @package _global_

# https://arxiv.org/pdf/1911.08947.pdf 참조

models:
  loss:
    _target_: ${loss_path}.DBPP_Loss
    alpha: 1.0
    beta: 10.0
    gamma: 1.0
    negative_ratio: 3.0
    eps: 1e-6
