# @package _global_

# https://arxiv.org/pdf/1911.08947.pdf 참조

models:
  head:
    _target_: ${head_path}.DBHead
    in_channels: 256                 # Input layer channel (실제 입력 feature와 동기화)
    upscale: 4                       # Output layer scale factor
    k: 50                            # The amplifying factor
    bias: False                      # Use bias or not in LayerNorm
    smooth: False                    # Use smooth or not in Upsample
    postprocess:
      thresh: 0.24                    # Binarization threshold
      box_thresh: 0.34                # Detection Box threshold
      max_candidates: 1000            # Limit the number of detection boxes
      use_polygon: True              # Detection Box Type (QUAD or POLY)
