# @package _global_

models:
  encoder:
    _target_: ocr.models.encoder.TimmBackbone
    model_name: 'convnext_base_384_in22ft1k'
    select_features: [0, 1, 2, 3]            # Output layer
    pretrained: true
