# @package _global_

models:
  encoder:
    _target_: ocr.models.encoder.TimmBackbone
    model_name: 'hrnet_w44.ms_in1k'
    select_features: [1, 2, 3, 4]            # Output layer, skip lowest resolution
    pretrained: true
