defaults:
  - _self_
  - preset: example
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_training"
project_name: "OCRProject"

wandb: True
exp_version: "v1.0"

resume: null

trainer:
  max_epochs: 10
  num_sanity_val_steps: 1
  log_every_n_steps: 50
  check_val_every_n_epoch: 1
  deterministic: True
# # smoke test
# trainer:
#   max_epochs: 1
#   num_sanity_val_steps: 0
#   log_every_n_steps: 1
#   check_val_every_n_epoch: 1
#   deterministic: True
#   limit_train_batches: 2
#   limit_val_batches: 2
#   limit_test_batches: 2
